# -*- coding: utf-8 -*-
"""pytorch-Refresh-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11925HF_1YiDoq5ERWDqY26TVvjxoV3Ns
"""

import torch

"""After importing the needed library it is important to define some tensors. the cell below shows how to define a tensor"""

zTensor = torch.zeros(size=(32, 3, 64, 64), requires_grad=True)
theTensor = torch.tensor([1, 2, 3, 4, 5, 5, 5, 5])
oneTensor = torch.ones(size=(32, 3, 128, 128), requires_grad=True)
randTensor = torch.randn(size=(32, 3, 128, 128), requires_grad=True)

print(zTensor.shape)
print(theTensor.shape)
print(oneTensor.shape)
print(randTensor.shape)

"""As it is shown in the prints it is really hard to define a tensor manually. zeros, ones, and rands are so useful in Neural Network creations. the torch creates the tensor in a shape we want and then fills it with zeros or ones or random numbers."""

print(zTensor.ndim)
print(theTensor.ndim)
print(oneTensor.ndim)
print(randTensor.ndim)

"""I say all the time: "it is so important to find the shape first." shape of a matrix or tensor tells us that if we write down the matrix on paper, how many rows and columns it would have (assume it is a 2D matrix or tensor), but dimensions show that if it is 1D or 2D or else, the count of numbers appearing in the Shape shows the number of dimensions."""

print(zTensor.dtype, theTensor.dtype, oneTensor.dtype, randTensor.dtype)

"""The prints show that when we use automated torch functions to create a tensor, it allocates float for that tensor in memory but when we specifictly fill the tensor with integer numbers it allocates int in memory"""

rand1 = torch.randn(size=(2, 2))
rand2 = torch. randn(size=(2, 2))
print(rand1)
print("-------------------")
print(rand2)

"""4 cells  bellow show 4 different operations applied on 2 tensors. all these 4 operators are working element-wise, but the 5th one is tensor multiplication or matmul operation which is not element-wise, obviously it works on tensors with same shape."""

rand3 = rand1 + rand2
print(rand3)

rand3 = rand1 - rand2
print(rand3)

rand3 = rand1 * rand2
print(rand3)

rand3 = rand1 / rand2
print(rand3)

rand3 = rand1 @ rand2
print(rand3)

rand4 = torch.randn(size=(3, 2))
rand5 = torch.randn(size=(2, 3))
rand6 = torch.zeros(size=(3, 3))
print(rand4)
print("--------------------------")
print(rand5)
print("--------------------------")
print(rand6)

"""The operator bellow shows the matmul, tensor multiplication. we should consider the tensor shapes,"""

rand6 = rand4 @ rand5
print(rand6)

"""in case of using this operator we will get an Error.
because this operator wants to multiply element wise but both tensors are not
in the same shape
"""

# rand6 = rand4 * rand5

oneReshaped = oneTensor.reshape(32, -1)
print(oneReshaped.shape)

oneReshaped2 = oneReshaped.reshape(32, 3, 128, 128)
print(oneReshaped2.shape)

randTensorSqueezed = randTensor.unsqueeze(0)
print(randTensorSqueezed.shape)
randTensorReverted = randTensorSqueezed.squeeze()
print(randTensorReverted.shape)

def describe_tensor(tensor):
  received = tensor
  print("The recieved tensor has ", received.shape, "shape")
  print("Also it is a ", received.ndim, "dimensional Tensor")
  print("We create a new tensor filled with random numbers")
  newTensor = torch.randn(size=received.shape)
  print("The element-wise multiplication of the recived and random is")
  result1 = newTensor * received
  print(result1[1])
  print("The element-wise division of the recived and random is")
  result2 = newTensor / received
  print(result2[1])
  print("Matrix Multiplication of these two would be like:")
  result3 = newTensor @ received
  print(result3[1])

  print("after Unsqeez it is:")
  receivedUnsqueezed = received.unsqueeze(0)
  print(receivedUnsqueezed.shape)
  print("after squeeze it is:")
  receivedSqueezed = receivedUnsqueezed.squeeze()
  print(receivedSqueezed.shape)
  if received.ndim == 4:
    receivedPermuted = received.permute(0, 3, 1, 2)
    print("after permute it is:")
    print(receivedPermuted.shape)

describe_tensor(randTensor)

